import Head from "next/head";
import CategoryContainer from "../components/common/CategoryContainer";
import Footer from "../components/common/Footer";
import Navbar from "../components/common/Navbar";
import Hero from "../components/home/Hero";
import styled from "styled-components";
import Presentation from "../components/common/Presentation";

const Container = styled.div`
  padding: 4%;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Container>
        <CategoryContainer />
        <Presentation />
      </Container>
      <Footer />
    </>
  );
}
